apiVersion: v1
kind: Secret
metadata:
  name: rsa-keys
  namespace: ride-hailing-dev
type: Opaque
data:
  private.pem: # Replace with the base64 encoded private key  
  public.pem: # Replace with the base64 encoded public key